Completed javascript-conditionals assignment
Aiden-Peace300/c0723-code-solutions pull request #10
Opened 2023-07-12 21:57 UTC by Aiden-Peace300

<img width="805" alt="image" src="https://github.com/Aiden-Peace300/c0723-code-solutions/assets/47370726/979bb21e-a1ef-4abc-82f7-bea6bdd4ffad">
<img width="803" alt="image" src="https://github.com/Aiden-Peace300/c0723-code-solutions/assets/47370726/69190b9b-9045-4447-b41a-a2fe4d677fda">

2023-07-12 22:05 UTC, shawnkost requested changes
Nicely done Aiden! A few tweaks here

2023-07-12 22:05 UTC, shawnkost commented on javascript-conditionals/main.js
> +    return true; // returning the boolean data type 'true'
You should never be able to drink and drive!

2023-07-12 22:05 UTC, shawnkost commented on javascript-conditionals/main.js
> +    if (pH >= 0 && pH < 7) {
Works, but the nested `if` statements isn't necessary. You're already checking if it's greater than 0, or less than 14 in another statements inside of here, so you don't need the nested.

2023-07-12 22:05 UTC, shawnkost commented on javascript-conditionals/main.js
> +    } else if (pH >= 7 && pH < 14) {
This should just be `> 7` && `<= 14`.

2023-07-12 22:05 UTC, shawnkost commented on javascript-conditionals/main.js
> +      return 'Genre not recognized. Choose between action, comedy, horror, drama, musical, or sci-fi';
Missing 1 more `case` clause for `sci-fi`

2023-07-12 22:28 UTC, Aiden-Peace300 commented
<img width="779" alt="image" src="https://github.com/Aiden-Peace300/c0723-code-solutions/assets/47370726/6839c90f-3ab9-43e3-b274-647dc634f84d">
<img width="804" alt="image" src="https://github.com/Aiden-Peace300/c0723-code-solutions/assets/47370726/b053cd8f-9552-4e48-ba77-9ff66a41c08d">

2023-07-12 22:35 UTC, shawnkost requested changes
One more change here Aiden!

2023-07-12 22:35 UTC, shawnkost commented on javascript-conditionals/main.js
> +  } else if (pH > 7 && pH < 14) {
What happens when `pH` is 14? 14 is still considered a base

2023-07-12 22:49 UTC, Aiden-Peace300 commented
<img width="782" alt="image" src="https://github.com/Aiden-Peace300/c0723-code-solutions/assets/47370726/39374f5d-15e8-4236-a72b-68975db83461">
<img width="793" alt="image" src="https://github.com/Aiden-Peace300/c0723-code-solutions/assets/47370726/0e070019-8e30-400d-b826-0942ba9d88b1">

2023-07-13 17:00 UTC, shawnkost approved these changes
👍🏻

2023-07-13 18:46 UTC, merged